version: '3'

services:
#######################################
#   Front-End Configuration
#######################################
  front_end:
    build:
      context: ./frontend/
    ports:
      - "8000:8000"
    expose:
      - "8000"
      
#######################################
#   Back-End Configuration
#######################################
  back_end:
    build:
      context: ./backend/
    ports:
      - "8888:8888"
    expose:
      - "8888"
